markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name:         
url: BuzzesLikeAFridge.github.io
description: He buzzes like a fridge/He's like a detuned radio.
twitter: donkeypetoncle
github: BuzzesLikeAFridge
gravatar_url:
